### ISSUE TITLE
Update Readme for Fellow Coders?

### ISSUE THREAD

**Issue by OdinsHat** [gszabi99/War-Thunder-Datamine#5]
I'm a War Thunder fan and fellow coder, but if I'm honest, I'm most interested in knowing a few things about this dataset:
1. How it's obtained (Spidering website/Game files)?
2. What format it's in?
3. What and how does Squirrel-lang fit into the equation (I'd not heard of it until I noticed this repo & Googled)?

Maybe you've put a lot of this info in a previous Reddit post? It'd be great if you could put it in the readme or at least link to it for some background?

Would be much appreciated. 🙂

**Comment by gszabi99** [comment]
1. Using a Windows-compatible variant of [kotiq's tools](https://github.com/kotiq/wt-tools), which are themselves updated versions of [klensy's tools](https://github.com/klensy/wt-tools).
2. Overwhelmingly in JSON (.blk / .blkx), but GitHub doesn't recognise it as its own file format, which is why Squirrel falsely appears to be the majority.
3. That's the language (.nut files) which Gaijin used for configuration files.

**Comment by OdinsHat** [comment]
Fantastic! Thank you @gszabi99 - you've been very helpful.

If you're still playing WT I look forward to being thoroughly beaten by you one day! I'm only level 9 and still struggling with being one-shotted even in my Soviet T-38 and German Panzers! 😆

Feel free to look me up...I play PS4 (Europe/UK) mostly GR/GA/NA, username `JoshAshiroLoki`

All the best.

Josh
